#mysql
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.177:3306/websocket_item?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: cd@123.com
    type: com.alibaba.druid.pool.DruidDataSource
    # ????



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.websocketitem.domain
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
logging:
  level:
    com.example.websocketitem.mapper: debug
server:
  port: 8088


