#mysql
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.177:3306/websocket_item?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: cd@123.com
    type: com.alibaba.druid.pool.DruidDataSource
    # ????




logging:
  level:
    com.chongdong.chongdong.mapper: debug
server:
  port: 8088


